-- [1]
SELECT NOME, ANO FROM FILMES;

-- [2] 
SELECT NOME, ANO FROM FILMES ORDER BY ANO;

--[3]
SELECT NOME, ANO, DURACAO FROM FILMES WHERE NOME = 'de volta para o futuro'

-- [4]
SELECT NOME, ANO, DURACAO FROM FILMES WHERE ANO = 1997;

-- [5]
SELECT NOME, ANO, DURACAO FROM FILMES WHERE ANO  > 2000;

-- [6]
SELECT NOME, ANO, DURACAO FROM FILMES WHERE DURACAO BETWEEN 101 AND 149 ORDER BY DURACAO;

-- [6.1]
SELECT NOME, ANO, DURACAO FROM FILMES WHERE DURACAO > 100 AND DURACAO < 150 ORDER BY DURACAO;

-- [7]
SELECT ANO, COUNT(*) AS QUANTIDADE FROM FILMES GROUP BY ANO ORDER BY QUANTIDADE DESC;

-- [8]
SELECT * FROM ATORES WHERE GENERO = 'M';

-- [9]
SELECT * FROM ATORES WHERE GENERO =  'F' ORDER BY PRIMEIRONOME;

-- [10] 
SELECT NOME, GENEROS.GENERO FROM ((FILMES INNER JOIN FILMESGENERO ON FILMES.ID = FILMESGENERO.IDFILME) INNER JOIN GENEROS ON GENEROS.ID = FILMESGENERO.IDGenero);

-- [11] 
SELECT NOME, GENEROS.GENERO FROM ((FILMES INNER JOIN FILMESGENERO ON FILMES.ID = FILMESGENERO.IDFILME) INNER JOIN GENEROS ON GENEROS.ID = FILMESGENERO.IDGenero) WHERE GENERO = 'Mistério';

-- [12]
SELECT NOME, ATORES.PRIMEIRONOME, ATORES.ULTIMONOME, ELENCOFILME.PAPEL FROM FILMES INNER JOIN ELENCOFILME ON FILMES.ID = ELENCOFILME.IDFILME INNER JOIN ATORES ON ELENCOFILME.IDATOR = ATORES.ID;

